[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["splitkci"]

[project]
name = "splitkci"
version = "0.3.0"
description = "SplitKCI implementation and experiments"
requires-python = ">= 3.9"
dependencies = []