problem_setup:
  task: 'ratinabox'
  ground_truth: 'H0'
  dim: 100
  measure: kci
  abc_holdout_sampling: separate
  ca_kernels: all
  abc_budget: 100
  min_grid_points: 100
pval:
  pval_estimation: 'wild'
  n_data_resamples: 1
  n_holdout_resamples: 1000
  n_points_wild_bootstrap: 1000
files:
  filename: 'test'
